apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd

spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lucasgmarques/argocd-web-app.git
    targetRevision: HEAD # The desired branch -> HEAD reffer to main or master
    path: k8s # Path inside the repository
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
